#!/bin/bash
# Idle cost reminder script for SageMaker Notebook Instance.
# Checks if the notebook has been idle for more than 60 minutes
# and writes a cost reminder file visible in the Jupyter file browser.
#
# This script is non-critical: errors are logged but it always exits 0
# so it never affects notebook operation.

IDLE_THRESHOLD_MINUTES=60
SAGEMAKER_DIR="/home/ec2-user/SageMaker"
REMINDER_FILE="${SAGEMAKER_DIR}/COST_REMINDER.md"
LOG_TAG="idle_check"

log_info()  { logger -t "$LOG_TAG" "$1"; }
log_error() { logger -t "$LOG_TAG" "ERROR: $1"; }

check_idle() {
    # Find the most recently modified file in the SageMaker directory,
    # excluding the reminder file itself and hidden files.
    local latest_mod
    latest_mod=$(find "$SAGEMAKER_DIR" \
        -maxdepth 3 \
        -not -name "$(basename "$REMINDER_FILE")" \
        -not -path '*/\.*' \
        -type f \
        -printf '%T@\n' 2>/dev/null | sort -rn | head -1)

    if [ -z "$latest_mod" ]; then
        # No files found — treat as idle since creation
        log_info "No user files found in ${SAGEMAKER_DIR}, treating as idle"
        echo "$IDLE_THRESHOLD_MINUTES"
        return 0
    fi

    local now
    now=$(date +%s)
    local last_mod_epoch
    last_mod_epoch=$(printf '%.0f' "$latest_mod")
    local idle_seconds=$(( now - last_mod_epoch ))
    local idle_minutes=$(( idle_seconds / 60 ))

    echo "$idle_minutes"
}

write_reminder() {
    cat > "$REMINDER_FILE" <<'EOF'
# ⚠️ Cost Reminder

This SageMaker Notebook instance has been **idle for over 60 minutes**.

You are still being charged while the instance is running.

## To stop costs

- **Stop** the notebook instance from the SageMaker console, or
- Run `cdk destroy --force` from the `infra/` directory to tear down all resources.

_This file is auto-generated by the idle check script and will be removed when activity resumes._
EOF
    log_info "Cost reminder written to ${REMINDER_FILE}"
}

remove_reminder() {
    if [ -f "$REMINDER_FILE" ]; then
        rm -f "$REMINDER_FILE"
        log_info "Cost reminder removed (activity detected)"
    fi
}

main() {
    local idle_minutes
    idle_minutes=$(check_idle) || {
        log_error "Failed to determine idle time"
        exit 0
    }

    log_info "Notebook idle for ${idle_minutes} minutes (threshold: ${IDLE_THRESHOLD_MINUTES})"

    if [ "$idle_minutes" -gt "$IDLE_THRESHOLD_MINUTES" ]; then
        write_reminder
    else
        remove_reminder
    fi
}

# Run and always exit 0 (non-critical)
main "$@" || log_error "Unexpected failure in main"
exit 0
