#!/bin/bash
set -e

# SageMaker Notebook Instance on-create lifecycle configuration script.
# Downloads the Titanic dataset, uploads it to S3, copies it locally,
# installs additional Python packages, and copies the demo notebook.
#
# Placeholders replaced by CDK at synth time:
#   __BUCKET_NAME__  — S3 bucket for the demo dataset

DATASET_URL="https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
BUCKET_NAME="__BUCKET_NAME__"
DATASET_S3_KEY="data/titanic.csv"
LOCAL_DATA_DIR="/home/ec2-user/SageMaker/data"
SAGEMAKER_DIR="/home/ec2-user/SageMaker"

# Download the Titanic dataset
wget -q "$DATASET_URL" -O /tmp/titanic.csv || {
    echo "ERROR: Failed to download dataset from $DATASET_URL" >&2
    exit 1
}

# Upload dataset to S3
aws s3 cp /tmp/titanic.csv "s3://${BUCKET_NAME}/${DATASET_S3_KEY}" || {
    echo "ERROR: Failed to upload dataset to S3 bucket ${BUCKET_NAME}" >&2
    exit 1
}

# Copy dataset locally
mkdir -p "$LOCAL_DATA_DIR"
cp /tmp/titanic.csv "${LOCAL_DATA_DIR}/titanic.csv" || {
    echo "ERROR: Failed to copy dataset to ${LOCAL_DATA_DIR}" >&2
    exit 1
}

# Install additional Python packages
pip install seaborn --quiet || {
    echo "ERROR: Failed to install seaborn" >&2
    exit 1
}

# Download demo notebook from S3 and copy to SageMaker directory
NOTEBOOK_S3_KEY="notebook/demo_notebook.ipynb"
aws s3 cp "s3://${BUCKET_NAME}/${NOTEBOOK_S3_KEY}" /tmp/demo_notebook.ipynb || {
    echo "ERROR: Failed to download demo notebook from S3 bucket ${BUCKET_NAME}" >&2
    exit 1
}
cp /tmp/demo_notebook.ipynb "${SAGEMAKER_DIR}/demo_notebook.ipynb" || {
    echo "ERROR: Failed to copy demo notebook to ${SAGEMAKER_DIR}" >&2
    exit 1
}

# Install idle cost reminder cron job (non-critical — errors must not fail the lifecycle config)
{
    IDLE_CHECK_DEST="/home/ec2-user/idle_check.sh"
    IDLE_CHECK_SCRIPT_DIR="$(cd "$(dirname "$0")" 2>/dev/null && pwd)"
    IDLE_CHECK_SOURCE="${IDLE_CHECK_SCRIPT_DIR}/idle_check.sh"

    # Try to copy from co-located script first, fall back to /tmp
    if [ -f "$IDLE_CHECK_SOURCE" ]; then
        cp "$IDLE_CHECK_SOURCE" "$IDLE_CHECK_DEST"
    elif [ -f "/tmp/idle_check.sh" ]; then
        cp "/tmp/idle_check.sh" "$IDLE_CHECK_DEST"
    else
        # Write the idle check script inline as a fallback
        cat > "$IDLE_CHECK_DEST" <<'IDLE_SCRIPT'
#!/bin/bash
IDLE_THRESHOLD_MINUTES=60
SAGEMAKER_DIR="/home/ec2-user/SageMaker"
REMINDER_FILE="${SAGEMAKER_DIR}/COST_REMINDER.md"
LOG_TAG="idle_check"
log_info()  { logger -t "$LOG_TAG" "$1"; }
log_error() { logger -t "$LOG_TAG" "ERROR: $1"; }
check_idle() {
    local latest_mod
    latest_mod=$(find "$SAGEMAKER_DIR" -maxdepth 3 -not -name "$(basename "$REMINDER_FILE")" -not -path '*/\.*' -type f -printf '%T@\n' 2>/dev/null | sort -rn | head -1)
    if [ -z "$latest_mod" ]; then
        log_info "No user files found in ${SAGEMAKER_DIR}, treating as idle"
        echo "$IDLE_THRESHOLD_MINUTES"
        return 0
    fi
    local now; now=$(date +%s)
    local last_mod_epoch; last_mod_epoch=$(printf '%.0f' "$latest_mod")
    local idle_seconds=$(( now - last_mod_epoch ))
    echo $(( idle_seconds / 60 ))
}
write_reminder() {
    cat > "$REMINDER_FILE" <<'REMINDER'
# ⚠️ Cost Reminder

This SageMaker Notebook instance has been **idle for over 60 minutes**.

You are still being charged while the instance is running.

## To stop costs

- **Stop** the notebook instance from the SageMaker console, or
- Run `cdk destroy --force` from the `infra/` directory to tear down all resources.

_This file is auto-generated by the idle check script and will be removed when activity resumes._
REMINDER
    log_info "Cost reminder written to ${REMINDER_FILE}"
}
remove_reminder() {
    if [ -f "$REMINDER_FILE" ]; then
        rm -f "$REMINDER_FILE"
        log_info "Cost reminder removed (activity detected)"
    fi
}
main() {
    local idle_minutes
    idle_minutes=$(check_idle) || { log_error "Failed to determine idle time"; exit 0; }
    log_info "Notebook idle for ${idle_minutes} minutes (threshold: ${IDLE_THRESHOLD_MINUTES})"
    if [ "$idle_minutes" -gt "$IDLE_THRESHOLD_MINUTES" ]; then
        write_reminder
    else
        remove_reminder
    fi
}
main "$@" || log_error "Unexpected failure in main"
exit 0
IDLE_SCRIPT
    fi

    chmod +x "$IDLE_CHECK_DEST"
    # Install cron job to run every 15 minutes
    (crontab -u ec2-user -l 2>/dev/null; echo "*/15 * * * * $IDLE_CHECK_DEST") | crontab -u ec2-user -
    echo "Idle check cron job installed."
} || echo "WARNING: Failed to install idle check cron job (non-critical)" >&2

echo "Lifecycle configuration completed successfully."
